// flow-typed signature: 639abcc574e0b50537f8174d88402ed8
// flow-typed version: <<STUB>>/canvg_v^1.5.3/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canvg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canvg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canvg/dist/browser/canvg' {
  declare module.exports: any;
}

declare module 'canvg/dist/browser/canvg.min' {
  declare module.exports: any;
}

declare module 'canvg/dist/node/canvg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canvg/dist/browser/canvg.js' {
  declare module.exports: $Exports<'canvg/dist/browser/canvg'>;
}
declare module 'canvg/dist/browser/canvg.min.js' {
  declare module.exports: $Exports<'canvg/dist/browser/canvg.min'>;
}
declare module 'canvg/dist/node/canvg.js' {
  declare module.exports: $Exports<'canvg/dist/node/canvg'>;
}
