// flow-typed signature: 0262f8413043b995b8291d7929ae954d
// flow-typed version: <<STUB>>/chart.js_v^1.1.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chart.js/Chart' {
  declare module.exports: any;
}

declare module 'chart.js/Chart.min' {
  declare module.exports: any;
}

declare module 'chart.js/gulpfile' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.Bar' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.Core' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.Doughnut' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.Line' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.PolarArea' {
  declare module.exports: any;
}

declare module 'chart.js/src/Chart.Radar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chart.js/Chart.js' {
  declare module.exports: $Exports<'chart.js/Chart'>;
}
declare module 'chart.js/Chart.min.js' {
  declare module.exports: $Exports<'chart.js/Chart.min'>;
}
declare module 'chart.js/gulpfile.js' {
  declare module.exports: $Exports<'chart.js/gulpfile'>;
}
declare module 'chart.js/src/Chart.Bar.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.Bar'>;
}
declare module 'chart.js/src/Chart.Core.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.Core'>;
}
declare module 'chart.js/src/Chart.Doughnut.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.Doughnut'>;
}
declare module 'chart.js/src/Chart.Line.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.Line'>;
}
declare module 'chart.js/src/Chart.PolarArea.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.PolarArea'>;
}
declare module 'chart.js/src/Chart.Radar.js' {
  declare module.exports: $Exports<'chart.js/src/Chart.Radar'>;
}
