// flow-typed signature: a35d367df78fc1739b474a5b3b03812e
// flow-typed version: <<STUB>>/cra-append-sw_v^2.6.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cra-append-sw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cra-append-sw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cra-append-sw/build/sw' {
  declare module.exports: any;
}

declare module 'cra-append-sw/sw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cra-append-sw/build/sw.js' {
  declare module.exports: $Exports<'cra-append-sw/build/sw'>;
}
declare module 'cra-append-sw/index' {
  declare module.exports: $Exports<'cra-append-sw'>;
}
declare module 'cra-append-sw/index.js' {
  declare module.exports: $Exports<'cra-append-sw'>;
}
declare module 'cra-append-sw/sw.js' {
  declare module.exports: $Exports<'cra-append-sw/sw'>;
}
