// flow-typed signature: 65d7d24b73f02ccb0db2ab42e1da8fc9
// flow-typed version: <<STUB>>/file-saver_v^2.0.0-rc.4/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-saver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-saver/dist/FileSaver' {
  declare module.exports: any;
}

declare module 'file-saver/dist/FileSaver.min' {
  declare module.exports: any;
}

declare module 'file-saver/src/FileSaver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-saver/dist/FileSaver.js' {
  declare module.exports: $Exports<'file-saver/dist/FileSaver'>;
}
declare module 'file-saver/dist/FileSaver.min.js' {
  declare module.exports: $Exports<'file-saver/dist/FileSaver.min'>;
}
declare module 'file-saver/src/FileSaver.js' {
  declare module.exports: $Exports<'file-saver/src/FileSaver'>;
}
