// flow-typed signature: 631f55443992114bf40e25b87297be3e
// flow-typed version: <<STUB>>/fsevents_v^2.0.7/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fsevents'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fsevents' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fsevents/fsevents' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fsevents/fsevents.js' {
  declare module.exports: $Exports<'fsevents/fsevents'>;
}
