// flow-typed signature: a86a45a9f5e24ab31a06057a355f5f2f
// flow-typed version: <<STUB>>/jspdf-autotable_v^3.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jspdf-autotable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jspdf-autotable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jspdf-autotable/dist/jspdf.plugin.autotable' {
  declare module.exports: any;
}

declare module 'jspdf-autotable/dist/jspdf.plugin.autotable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jspdf-autotable/dist/jspdf.plugin.autotable.js' {
  declare module.exports: $Exports<'jspdf-autotable/dist/jspdf.plugin.autotable'>;
}
declare module 'jspdf-autotable/dist/jspdf.plugin.autotable.min.js' {
  declare module.exports: $Exports<'jspdf-autotable/dist/jspdf.plugin.autotable.min'>;
}
