// flow-typed signature: 8c5abe091b53df9a86b42d00dac16d55
// flow-typed version: <<STUB>>/jspdf_v^1.5.3/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jspdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jspdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jspdf/dist/jspdf.debug' {
  declare module.exports: any;
}

declare module 'jspdf/dist/jspdf.min' {
  declare module.exports: any;
}

declare module 'jspdf/dist/jspdf.node.debug' {
  declare module.exports: any;
}

declare module 'jspdf/dist/jspdf.node.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jspdf/dist/jspdf.debug.js' {
  declare module.exports: $Exports<'jspdf/dist/jspdf.debug'>;
}
declare module 'jspdf/dist/jspdf.min.js' {
  declare module.exports: $Exports<'jspdf/dist/jspdf.min'>;
}
declare module 'jspdf/dist/jspdf.node.debug.js' {
  declare module.exports: $Exports<'jspdf/dist/jspdf.node.debug'>;
}
declare module 'jspdf/dist/jspdf.node.min.js' {
  declare module.exports: $Exports<'jspdf/dist/jspdf.node.min'>;
}
