// flow-typed signature: b41dccd99da7d0b964c56d303960f67c
// flow-typed version: <<STUB>>/pre-push_v^0.1.1/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pre-push'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pre-push' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pre-push/install' {
  declare module.exports: any;
}

declare module 'pre-push/test' {
  declare module.exports: any;
}

declare module 'pre-push/uninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pre-push/index' {
  declare module.exports: $Exports<'pre-push'>;
}
declare module 'pre-push/index.js' {
  declare module.exports: $Exports<'pre-push'>;
}
declare module 'pre-push/install.js' {
  declare module.exports: $Exports<'pre-push/install'>;
}
declare module 'pre-push/test.js' {
  declare module.exports: $Exports<'pre-push/test'>;
}
declare module 'pre-push/uninstall.js' {
  declare module.exports: $Exports<'pre-push/uninstall'>;
}
