// flow-typed signature: e5e572c4ce5f12a06816f8da14807210
// flow-typed version: <<STUB>>/react-svg-piechart_v^2.4.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-piechart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-piechart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-piechart/es/Circle' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/es' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/es/Sector' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/es/Sectors' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/lib/Circle' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/lib' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/lib/Sector' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/lib/Sectors' {
  declare module.exports: any;
}

declare module 'react-svg-piechart/umd/react-svg-piechart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-piechart/es/Circle/index' {
  declare module.exports: $Exports<'react-svg-piechart/es/Circle'>;
}
declare module 'react-svg-piechart/es/Circle/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/es/Circle'>;
}
declare module 'react-svg-piechart/es/index' {
  declare module.exports: $Exports<'react-svg-piechart/es'>;
}
declare module 'react-svg-piechart/es/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/es'>;
}
declare module 'react-svg-piechart/es/Sector/index' {
  declare module.exports: $Exports<'react-svg-piechart/es/Sector'>;
}
declare module 'react-svg-piechart/es/Sector/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/es/Sector'>;
}
declare module 'react-svg-piechart/es/Sectors/index' {
  declare module.exports: $Exports<'react-svg-piechart/es/Sectors'>;
}
declare module 'react-svg-piechart/es/Sectors/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/es/Sectors'>;
}
declare module 'react-svg-piechart/lib/Circle/index' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Circle'>;
}
declare module 'react-svg-piechart/lib/Circle/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Circle'>;
}
declare module 'react-svg-piechart/lib/index' {
  declare module.exports: $Exports<'react-svg-piechart/lib'>;
}
declare module 'react-svg-piechart/lib/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/lib'>;
}
declare module 'react-svg-piechart/lib/Sector/index' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Sector'>;
}
declare module 'react-svg-piechart/lib/Sector/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Sector'>;
}
declare module 'react-svg-piechart/lib/Sectors/index' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Sectors'>;
}
declare module 'react-svg-piechart/lib/Sectors/index.js' {
  declare module.exports: $Exports<'react-svg-piechart/lib/Sectors'>;
}
declare module 'react-svg-piechart/umd/react-svg-piechart.js' {
  declare module.exports: $Exports<'react-svg-piechart/umd/react-svg-piechart'>;
}
