// flow-typed signature: 47485fe525aa7b6f5ea0b21d8a2f8526
// flow-typed version: <<STUB>>/react-dom-confetti_v0.0.10/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom-confetti'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom-confetti' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom-confetti/lib/confetti' {
  declare module.exports: any;
}

declare module 'react-dom-confetti/src/confetti' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom-confetti/lib/confetti.js' {
  declare module.exports: $Exports<'react-dom-confetti/lib/confetti'>;
}
declare module 'react-dom-confetti/src/confetti.js' {
  declare module.exports: $Exports<'react-dom-confetti/src/confetti'>;
}
