// flow-typed signature: 53339c4a949111fa21209bb5c05d8847
// flow-typed version: <<STUB>>/react-chartjs_v^1.2.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-chartjs/dist/react-chartjs' {
  declare module.exports: any;
}

declare module 'react-chartjs/dist/react-chartjs.min' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/bar' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/core' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/doughnut' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/line' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/pie' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/polar-area' {
  declare module.exports: any;
}

declare module 'react-chartjs/lib/radar' {
  declare module.exports: any;
}

declare module 'react-chartjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-chartjs/dist/react-chartjs.js' {
  declare module.exports: $Exports<'react-chartjs/dist/react-chartjs'>;
}
declare module 'react-chartjs/dist/react-chartjs.min.js' {
  declare module.exports: $Exports<'react-chartjs/dist/react-chartjs.min'>;
}
declare module 'react-chartjs/index' {
  declare module.exports: $Exports<'react-chartjs'>;
}
declare module 'react-chartjs/index.js' {
  declare module.exports: $Exports<'react-chartjs'>;
}
declare module 'react-chartjs/lib/bar.js' {
  declare module.exports: $Exports<'react-chartjs/lib/bar'>;
}
declare module 'react-chartjs/lib/core.js' {
  declare module.exports: $Exports<'react-chartjs/lib/core'>;
}
declare module 'react-chartjs/lib/doughnut.js' {
  declare module.exports: $Exports<'react-chartjs/lib/doughnut'>;
}
declare module 'react-chartjs/lib/line.js' {
  declare module.exports: $Exports<'react-chartjs/lib/line'>;
}
declare module 'react-chartjs/lib/pie.js' {
  declare module.exports: $Exports<'react-chartjs/lib/pie'>;
}
declare module 'react-chartjs/lib/polar-area.js' {
  declare module.exports: $Exports<'react-chartjs/lib/polar-area'>;
}
declare module 'react-chartjs/lib/radar.js' {
  declare module.exports: $Exports<'react-chartjs/lib/radar'>;
}
declare module 'react-chartjs/webpack.config.js' {
  declare module.exports: $Exports<'react-chartjs/webpack.config'>;
}
