// flow-typed signature: 3eca051995b169c45651faba483fbc07
// flow-typed version: <<STUB>>/redux-observable_v^1.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-observable/dist/redux-observable' {
  declare module.exports: any;
}

declare module 'redux-observable/dist/redux-observable.min' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/ActionsObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/combineEpics' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/createEpicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/operators' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/StateObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/utils/console' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/ActionsObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/combineEpics' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/createEpicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/index' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/operators' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/StateObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/esm/utils/console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-observable/dist/redux-observable.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable'>;
}
declare module 'redux-observable/dist/redux-observable.min.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable.min'>;
}
declare module 'redux-observable/lib/cjs/ActionsObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/ActionsObservable'>;
}
declare module 'redux-observable/lib/cjs/combineEpics.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/combineEpics'>;
}
declare module 'redux-observable/lib/cjs/createEpicMiddleware.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/createEpicMiddleware'>;
}
declare module 'redux-observable/lib/cjs/index.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/index'>;
}
declare module 'redux-observable/lib/cjs/operators.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/operators'>;
}
declare module 'redux-observable/lib/cjs/StateObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/StateObservable'>;
}
declare module 'redux-observable/lib/cjs/utils/console.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/utils/console'>;
}
declare module 'redux-observable/lib/esm/ActionsObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/ActionsObservable'>;
}
declare module 'redux-observable/lib/esm/combineEpics.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/combineEpics'>;
}
declare module 'redux-observable/lib/esm/createEpicMiddleware.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/createEpicMiddleware'>;
}
declare module 'redux-observable/lib/esm/index.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/index'>;
}
declare module 'redux-observable/lib/esm/operators.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/operators'>;
}
declare module 'redux-observable/lib/esm/StateObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/StateObservable'>;
}
declare module 'redux-observable/lib/esm/utils/console.js' {
  declare module.exports: $Exports<'redux-observable/lib/esm/utils/console'>;
}
