// flow-typed signature: 251a0e52c9feda97334d9a5ced457832
// flow-typed version: <<STUB>>/source-map-explorer_v^1.6.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-explorer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-explorer/test' {
  declare module.exports: any;
}

declare module 'source-map-explorer/testdata/foo.min.inline-map' {
  declare module.exports: any;
}

declare module 'source-map-explorer/testdata/foo.min' {
  declare module.exports: any;
}

declare module 'source-map-explorer/testdata/foo.min.no-map' {
  declare module.exports: any;
}

declare module 'source-map-explorer/vendor/webtreemap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-explorer/index' {
  declare module.exports: $Exports<'source-map-explorer'>;
}
declare module 'source-map-explorer/index.js' {
  declare module.exports: $Exports<'source-map-explorer'>;
}
declare module 'source-map-explorer/test.js' {
  declare module.exports: $Exports<'source-map-explorer/test'>;
}
declare module 'source-map-explorer/testdata/foo.min.inline-map.js' {
  declare module.exports: $Exports<'source-map-explorer/testdata/foo.min.inline-map'>;
}
declare module 'source-map-explorer/testdata/foo.min.js' {
  declare module.exports: $Exports<'source-map-explorer/testdata/foo.min'>;
}
declare module 'source-map-explorer/testdata/foo.min.no-map.js' {
  declare module.exports: $Exports<'source-map-explorer/testdata/foo.min.no-map'>;
}
declare module 'source-map-explorer/vendor/webtreemap.js' {
  declare module.exports: $Exports<'source-map-explorer/vendor/webtreemap'>;
}
