// flow-typed signature: 37fdd6b8b18b997b2cdc429e04986f24
// flow-typed version: <<STUB>>/source-map-explorer_v^1.8.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-explorer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-explorer/vendor/webtreemap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-explorer/index' {
  declare module.exports: $Exports<'source-map-explorer'>;
}
declare module 'source-map-explorer/index.js' {
  declare module.exports: $Exports<'source-map-explorer'>;
}
declare module 'source-map-explorer/vendor/webtreemap.js' {
  declare module.exports: $Exports<'source-map-explorer/vendor/webtreemap'>;
}
