// flow-typed signature: a49f85454e48f25c6ce4ed36a02ab5f1
// flow-typed version: <<STUB>>/thyme-connect_v^1.0.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thyme-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thyme-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thyme-connect/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thyme-connect/main.js' {
  declare module.exports: $Exports<'thyme-connect/main'>;
}
