export default [
  { key: 'af', text: 'Afghanistan' },
  { key: 'ax', text: 'Aland Islands' },
  { key: 'al', text: 'Albania' },
  { key: 'dz', text: 'Algeria' },
  { key: 'as', text: 'American Samoa' },
  { key: 'ad', text: 'Andorra' },
  { key: 'ao', text: 'Angola' },
  { key: 'ai', text: 'Anguilla' },
  { key: 'ag', text: 'Antigua' },
  { key: 'ar', text: 'Argentina' },
  { key: 'am', text: 'Armenia' },
  { key: 'aw', text: 'Aruba' },
  { key: 'au', text: 'Australia' },
  { key: 'at', text: 'Austria' },
  { key: 'az', text: 'Azerbaijan' },
  { key: 'bs', text: 'Bahamas' },
  { key: 'bh', text: 'Bahrain' },
  { key: 'bd', text: 'Bangladesh' },
  { key: 'bb', text: 'Barbados' },
  { key: 'by', text: 'Belarus' },
  { key: 'be', text: 'Belgium' },
  { key: 'bz', text: 'Belize' },
  { key: 'bj', text: 'Benin' },
  { key: 'bm', text: 'Bermuda' },
  { key: 'bt', text: 'Bhutan' },
  { key: 'bo', text: 'Bolivia' },
  { key: 'ba', text: 'Bosnia' },
  { key: 'bw', text: 'Botswana' },
  { key: 'bv', text: 'Bouvet Island' },
  { key: 'br', text: 'Brazil' },
  { key: 'vg', text: 'British Virgin Islands' },
  { key: 'bn', text: 'Brunei' },
  { key: 'bg', text: 'Bulgaria' },
  { key: 'bf', text: 'Burkina Faso' },
  { key: 'bi', text: 'Burundi' },
  { key: 'tc', text: 'Caicos Islands' },
  { key: 'kh', text: 'Cambodia' },
  { key: 'cm', text: 'Cameroon' },
  { key: 'ca', text: 'Canada' },
  { key: 'cv', text: 'Cape Verde' },
  { key: 'ky', text: 'Cayman Islands' },
  { key: 'cf', text: 'Central African Republic' },
  { key: 'td', text: 'Chad' },
  { key: 'cl', text: 'Chile' },
  { key: 'cn', text: 'China' },
  { key: 'cx', text: 'Christmas Island' },
  { key: 'cc', text: 'Cocos Islands' },
  { key: 'co', text: 'Colombia' },
  { key: 'km', text: 'Comoros' },
  { key: 'cd', text: 'Congo' },
  { key: 'cg', text: 'Congo Brazzaville' },
  { key: 'ck', text: 'Cook Islands' },
  { key: 'cr', text: 'Costa Rica' },
  { key: 'ci', text: 'Cote Divoire' },
  { key: 'hr', text: 'Croatia' },
  { key: 'cu', text: 'Cuba' },
  { key: 'cy', text: 'Cyprus' },
  { key: 'cz', text: 'Czech Republic' },
  { key: 'dk', text: 'Denmark' },
  { key: 'dj', text: 'Djibouti' },
  { key: 'dm', text: 'Dominica' },
  { key: 'do', text: 'Dominican Republic' },
  { key: 'ec', text: 'Ecuador' },
  { key: 'eg', text: 'Egypt' },
  { key: 'sv', text: 'El Salvador' },
  { key: 'gb', text: 'England' },
  { key: 'gq', text: 'Equatorial Guinea' },
  { key: 'er', text: 'Eritrea' },
  { key: 'ee', text: 'Estonia' },
  { key: 'et', text: 'Ethiopia' },
  { key: 'eu', text: 'European Union' },
  { key: 'fk', text: 'Falkland Islands' },
  { key: 'fo', text: 'Faroe Islands' },
  { key: 'fj', text: 'Fiji' },
  { key: 'fi', text: 'Finland' },
  { key: 'fr', text: 'France' },
  { key: 'gf', text: 'French Guiana' },
  { key: 'pf', text: 'French Polynesia' },
  { key: 'tf', text: 'French Territories' },
  { key: 'ga', text: 'Gabon' },
  { key: 'gm', text: 'Gambia' },
  { key: 'ge', text: 'Georgia' },
  { key: 'de', text: 'Germany' },
  { key: 'gh', text: 'Ghana' },
  { key: 'gi', text: 'Gibraltar' },
  { key: 'gr', text: 'Greece' },
  { key: 'gl', text: 'Greenland' },
  { key: 'gd', text: 'Grenada' },
  { key: 'gp', text: 'Guadeloupe' },
  { key: 'gu', text: 'Guam' },
  { key: 'gt', text: 'Guatemala' },
  { key: 'gn', text: 'Guinea' },
  { key: 'gw', text: 'Guinea-Bissau' },
  { key: 'gy', text: 'Guyana' },
  { key: 'ht', text: 'Haiti' },
  { key: 'hm', text: 'Heard Island' },
  { key: 'hn', text: 'Honduras' },
  { key: 'hk', text: 'Hong Kong' },
  { key: 'hu', text: 'Hungary' },
  { key: 'is', text: 'Iceland' },
  { key: 'in', text: 'India' },
  { key: 'io', text: 'Indian Ocean Territory' },
  { key: 'id', text: 'Indonesia' },
  { key: 'ir', text: 'Iran' },
  { key: 'iq', text: 'Iraq' },
  { key: 'ie', text: 'Ireland' },
  { key: 'il', text: 'Israel' },
  { key: 'it', text: 'Italy' },
  { key: 'jm', text: 'Jamaica' },
  { key: 'jp', text: 'Japan' },
  { key: 'jo', text: 'Jordan' },
  { key: 'kz', text: 'Kazakhstan' },
  { key: 'ke', text: 'Kenya' },
  { key: 'ki', text: 'Kiribati' },
  { key: 'kw', text: 'Kuwait' },
  { key: 'kg', text: 'Kyrgyzstan' },
  { key: 'la', text: 'Laos' },
  { key: 'lv', text: 'Latvia' },
  { key: 'lb', text: 'Lebanon' },
  { key: 'ls', text: 'Lesotho' },
  { key: 'lr', text: 'Liberia' },
  { key: 'ly', text: 'Libya' },
  { key: 'li', text: 'Liechtenstein' },
  { key: 'lt', text: 'Lithuania' },
  { key: 'lu', text: 'Luxembourg' },
  { key: 'mo', text: 'Macau' },
  { key: 'mk', text: 'Macedonia' },
  { key: 'mg', text: 'Madagascar' },
  { key: 'mw', text: 'Malawi' },
  { key: 'my', text: 'Malaysia' },
  { key: 'mv', text: 'Maldives' },
  { key: 'ml', text: 'Mali' },
  { key: 'mt', text: 'Malta' },
  { key: 'mh', text: 'Marshall Islands' },
  { key: 'mq', text: 'Martinique' },
  { key: 'mr', text: 'Mauritania' },
  { key: 'mu', text: 'Mauritius' },
  { key: 'yt', text: 'Mayotte' },
  { key: 'mx', text: 'Mexico' },
  { key: 'fm', text: 'Micronesia' },
  { key: 'md', text: 'Moldova' },
  { key: 'mc', text: 'Monaco' },
  { key: 'mn', text: 'Mongolia' },
  { key: 'me', text: 'Montenegro' },
  { key: 'ms', text: 'Montserrat' },
  { key: 'ma', text: 'Morocco' },
  { key: 'mz', text: 'Mozambique' },
  { key: 'na', text: 'Namibia' },
  { key: 'nr', text: 'Nauru' },
  { key: 'np', text: 'Nepal' },
  { key: 'nl', text: 'Netherlands' },
  { key: 'an', text: 'Netherlands Antilles' },
  { key: 'nc', text: 'New Caledonia' },
  { key: 'pg', text: 'New Guinea' },
  { key: 'nz', text: 'New Zealand' },
  { key: 'ni', text: 'Nicaragua' },
  { key: 'ne', text: 'Niger' },
  { key: 'ng', text: 'Nigeria' },
  { key: 'nu', text: 'Niue' },
  { key: 'nf', text: 'Norfolk Island' },
  { key: 'kp', text: 'North Korea' },
  { key: 'mp', text: 'Northern Mariana Islands' },
  { key: 'no', text: 'Norway' },
  { key: 'om', text: 'Oman' },
  { key: 'pk', text: 'Pakistan' },
  { key: 'pw', text: 'Palau' },
  { key: 'ps', text: 'Palestine' },
  { key: 'pa', text: 'Panama' },
  { key: 'py', text: 'Paraguay' },
  { key: 'pe', text: 'Peru' },
  { key: 'ph', text: 'Philippines' },
  { key: 'pn', text: 'Pitcairn Islands' },
  { key: 'pl', text: 'Poland' },
  { key: 'pt', text: 'Portugal' },
  { key: 'pr', text: 'Puerto Rico' },
  { key: 'qa', text: 'Qatar' },
  { key: 're', text: 'Reunion' },
  { key: 'ro', text: 'Romania' },
  { key: 'ru', text: 'Russia' },
  { key: 'rw', text: 'Rwanda' },
  { key: 'sh', text: 'Saint Helena' },
  { key: 'kn', text: 'Saint Kitts and Nevis' },
  { key: 'lc', text: 'Saint Lucia' },
  { key: 'pm', text: 'Saint Pierre' },
  { key: 'vc', text: 'Saint Vincent' },
  { key: 'ws', text: 'Samoa' },
  { key: 'sm', text: 'San Marino' },
  { key: 'gs', text: 'Sandwich Islands' },
  { key: 'st', text: 'Sao Tome' },
  { key: 'sa', text: 'Saudi Arabia' },
  { key: 'sn', text: 'Senegal' },
  { key: 'cs', text: 'Serbia' },
  { key: 'rs', text: 'Serbia' },
  { key: 'sc', text: 'Seychelles' },
  { key: 'sl', text: 'Sierra Leone' },
  { key: 'sg', text: 'Singapore' },
  { key: 'sk', text: 'Slovakia' },
  { key: 'si', text: 'Slovenia' },
  { key: 'sb', text: 'Solomon Islands' },
  { key: 'so', text: 'Somalia' },
  { key: 'za', text: 'South Africa' },
  { key: 'kr', text: 'South Korea' },
  { key: 'es', text: 'Spain' },
  { key: 'lk', text: 'Sri Lanka' },
  { key: 'sd', text: 'Sudan' },
  { key: 'sr', text: 'Suriname' },
  { key: 'sj', text: 'Svalbard' },
  { key: 'sz', text: 'Swaziland' },
  { key: 'se', text: 'Sweden' },
  { key: 'ch', text: 'Switzerland' },
  { key: 'sy', text: 'Syria' },
  { key: 'tw', text: 'Taiwan' },
  { key: 'tj', text: 'Tajikistan' },
  { key: 'tz', text: 'Tanzania' },
  { key: 'th', text: 'Thailand' },
  { key: 'tl', text: 'Timorleste' },
  { key: 'tg', text: 'Togo' },
  { key: 'tk', text: 'Tokelau' },
  { key: 'to', text: 'Tonga' },
  { key: 'tt', text: 'Trinidad' },
  { key: 'tn', text: 'Tunisia' },
  { key: 'tr', text: 'Turkey' },
  { key: 'tm', text: 'Turkmenistan' },
  { key: 'tv', text: 'Tuvalu' },
  { key: 'ug', text: 'Uganda' },
  { key: 'ua', text: 'Ukraine' },
  { key: 'ae', text: 'United Arab Emirates' },
  { key: 'us', text: 'United States' },
  { key: 'uy', text: 'Uruguay' },
  { key: 'um', text: 'Us Minor Islands' },
  { key: 'vi', text: 'Us Virgin Islands' },
  { key: 'uz', text: 'Uzbekistan' },
  { key: 'vu', text: 'Vanuatu' },
  { key: 'va', text: 'Vatican City' },
  { key: 've', text: 'Venezuela' },
  { key: 'vn', text: 'Vietnam' },
  { key: 'wf', text: 'Wallis and Futuna' },
  { key: 'eh', text: 'Western Sahara' },
  { key: 'ye', text: 'Yemen' },
  { key: 'zm', text: 'Zambia' },
  { key: 'zw', text: 'Zimbabwe' },
];
